### ISSUE TITLE
getParsedError doesn't work properly with viem ^2.8.16

### ISSUE THREAD

**Issue by rin-st** [scaffold-eth/create-eth#18]
on last viem versions (2.9.25+) `e.details` contains the whole error message

https://github.com/scaffold-eth/se-2-challenges/pull/174#issuecomment-2088846232 

although I didn't find in their [changelog](https://github.com/wevm/viem/blob/main/src/CHANGELOG.md) what could cause it.

I fixed a problem for now by locking `viem` to `2.8.16` but looks like we need to rewrite `getParsedError` a bit.

Opening an issue here since in main se-2 we have `yarn.lock`.

Probably I'm missing something, you can check it here [sre challenge 1 wagmi 2 backmerge](https://github.com/scaffold-eth/se-2-challenges/pull/174)

[1df6640](https://github.com/scaffold-eth/se-2-challenges/pull/174/commits/1df6640d96212ec39a275a75bbaf3a1cf90d4f1e) - normal error messages

[c5f95cc](https://github.com/scaffold-eth/se-2-challenges/pull/174/commits/c5f95cc7205846d9cb5a84eaaa9b8e0ded40566b) - broken error messages

**Comment by technophile-04** [comment]
Fixed at https://github.com/scaffold-eth/scaffold-eth-2/pull/849#discussion_r1605966528 🙌
