### ISSUE TITLE
npx create-eth@latest fails on node v20+

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/create-eth#49]
### Description : 

To be more particular it happens when the npm version is 10.4.0 or later. 

Hacky solution for now is to run it with `--ignore-scripts` flag: 

```shell
npx create-eth@latest --ignore-scripts
```

or use 18 or below versions of node

### Cause: 

The main problem is `husky`. 

The thing is that husky doesn't play nicely with yarn v2+ since yarn does not have `prepare`  life cycle method checkout [this](https://github.com/typicode/husky/pull/1371) so we have to rely on `postinstall` lifecycle as mentioned in the docs checkout #46. 

But using `postinstall` is bad idea because whenever some one does `npx create-eth@latest` the `postinstall` script runs and since we have `postinstall: husky init` it will fail on users computer because while we bundle cli we don't include husky init since it's a dev dependency. 

Workaround to above solution was to use `pinst` which we did in #46, what `pinst` does is before publishing your package to npm it edit's your `package.json` and renames `postinstall` => `_postinstall` so that it does not runs on users computers. 

<details>

<summary>
Example : 
</summary>

You can navigate to `~/.npm/_npx/{id}/node_modules/create-eth/package.json`: 

![Screenshot 2024-06-13 at 11 16 09 PM](https://github.com/scaffold-eth/create-eth/assets/80153681/2a3dce50-97ec-40b2-9678-92f3ff44286d)

</details>

Now in ideal world with magic of `pinst` on users computer we wont run `husky init` since we renamed  it to `_postinstall` script but the thing is for some wired reason 10.4.0 and later npm cli actually runs `_postinstall`  checkout https://github.com/typicode/pinst/issues/23 and https://github.com/npm/cli/issues/7322

### Solution: 

Ditch husky since with yarn v2+ it requires addition of  `postinstall`  and we don't want to do it since `postinstall` runs on users computer too, We could move husky from devDependency to dependency but I don't like it and not that worth it. 

Use other alternatives on my research I found [lefthook](https://github.com/evilmartians/lefthook) to be best, will probably make a PR migrating to it

**Comment by technophile-04** [comment]
Fixed at #51

**Comment by djcsdy** [comment]
Here is a [write-up of what the underlying problem was here](https://gist.github.com/djcsdy/2f5a287b3ba16f2a8f0312f45588e6ce).
