### ISSUE TITLE
formatting instance

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/create-eth#77]
### Description: 

We could tinker more on https://github.com/scaffold-eth/create-eth/pull/55#discussion_r1642976898

Or I have been thinking this for while, what if we don't ask the user for installing dependency and we directly do it? 

If people really want to skip then they can use our hidden `--skip` flag. 

This will remove prettier burden from us, and also we don't need ship prettier and its plugins as main dependencies while pushing the package to npm. 

Some other create cli eg npx create-next-app does seem to do same. 

If showing user just "Installing dependencies..." for a while feels strange, I think with Listr2 we could also output some ongoing logs of `yarn install` just to feel more dynamic

**Comment by carletex** [comment]
> If people really want to skip then they can use our hidden --skip flag.

I think I like this idea a lot :)

less clutter in the CLI options, and less headaches for us with the formatting.

I give it a +:100:

**Comment by technophile-04** [comment]
Completed in #76
