### ISSUE TITLE
Remove «None» option for 3rd party extensions with contracts

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/create-eth#93]
We just merged https://github.com/scaffold-eth/create-eth/pull/90

When a 3rd part extension provides a contract it doesn't make sense to allow the user to select the «None» option when selecting solidity frameworks.

Let's remove the «none» option when this happens.

From #90, an idea on how to go about it:

> If we want to follow this path, the change of workflow might not be too difficult tho... instead of validating the extension in parseArgumentsIntoOptions we could copy it down already (or even parse it with a request to Github!) and check if foundry / hardhat folder exists. If so, we change the rawOptions variable (passed to promptForMissingOptions) where we can conditionally render/not render the Null option.

Let's try to go with the simplest path here.

**Comment by technophile-04** [comment]
> If we want to follow this path, the change of workflow might not be too difficult tho... instead of validating the extension in parseArgumentsIntoOptions we could copy it down already (or even parse it with a request to Github!) and check if foundry / hardhat folder exists. If so, we change the rawOptions variable (passed to promptForMissingOptions) where we can conditionally render/not render the Null option. 

+1 for this! @rin-st if you haven't started yet I would love to tackle it 🙌

**Comment by rin-st** [comment]
@technophile-04 sure, take it!
